version: '3.8'

services:
  node:
    image: node:18.13
    volumes:
      - .:/app
      - next:/app/.next
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true

volumes:
  next:
  node_modules:
